name: flutter_img_picker
description:  Flutter plugin for file picker.
version: 0.0.1
homepage: https://github.com/wenchaosong/FlutterImagePicker

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # https://pub.dev/packages/photo_manager
  photo_manager: ^0.6.0
